<?php echo $this->partial('admin/nav.phtml', 'storage') ; ?>

<?php $files = $this->files; ?>
<div id="admin-user-manager">
    <table class="table">
        <thead>
        <tr>
            <th class="w-50">#</th>
            <th>Name</th>
            <th>Size</th>
            <th>Creation Date</th>
            <th>Modified Date</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($files as $file){?>
        <tr data-id="<?php echo $file->getId(); ?>">
            <td><?php echo $file->getId(); ?></td>
            <td><a target="_blank" href="<?php echo $file->getHref(); ?>"><?php echo $file->getName(); ?></a></td>
            <td><?php echo round($file->getSize() / 1024, 1); ?> Kb</td>
            <td><?php echo $file->getTimeCreate(); ?></td>
            <td><?php echo $file->getTimeModified(); ?></td>
            <td>
                <?php echo $this->partial('blocks/btn/tr_delete.phtml', 'admin', array('url' => 'storage/admin/deletefile')) ; ?>
            </td>
        </tr>
            <?php }?>
        </tbody>
    </table>
</div>

