<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta();  ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script> var publicUrl = '<?php echo $this->getPublicUrl(); ?>'</script>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>

<body>

<div class="container">
    <div>
        <?php foreach($this->menu as $key=>$a){?>
            <a style="margin-right: 20px;" href="<?php echo $a; ?>"><?php echo $key?></a>
        <?php }?>
    </div>



    <?php echo $this->layout()->content ; ?>
</div>
</body>

</html>
