

<script>
    $(function(){
        $('body').on('click', '.btn-delete', function(){
            var $block = $(this).closest('tr');

            $.ajax({type: 'POST',
                datatype:"json",
                url: publicUrl+ 'user/admin/deleteuser',
                data: {'user_id' :$block.attr('data-id')},
                success: function(data){
                    if(data.success){
                        $block.remove();
                    }
                }
            });
            return false;
        }) ;

        $('body').on('click', '.btn-edit', function(){
           $('#myModal').modal('show');
        });
    })
</script>

<?php echo $this->partial('admin/nav.phtml', 'user') ; ?>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php $users = $this->users; ?>
<table class="table">
    <thead>
    <tr>
        <th class="w-50">#</th>
        <th>Email</th>
        <th>Groups</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user){?>
        <tr data-id="<?php echo $user->getId(); ?>">
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $user->getEmail(); ?></td>
            <td><?php echo $user->getGroups()->getStringImplodeColumn('name');?><a href="#" class="btn-edit">Edit</a></td>
            <td><button class="btn btn-danger btn-delete">Delete</button></td>
        </tr>
        <?php }?>
    </tbody>
</table>

