<?php $action = $this->getActionName(); ?>
<ul class="nav nav-tabs">
    <li class="<?php if($action == 'manager') echo 'active';?>" ><a href="<?php echo $this->getRouteUrl('admin_user_manager'); ?>">Manager</a></li>
    <li class="<?php if($action == 'options') echo 'active';?>"><a href="<?php echo $this->getRouteUrl('admin_user_options'); ?>">Options</a></li>
    <li class="<?php if($action == 'groups') echo 'active';?>"><a href="<?php echo $this->getRouteUrl('admin_user_groups'); ?>">Groups</a></li>
</ul>