
<script type="text/javascript">
    $(function(){
        $('[name="type_account"]').on('change', function(){
            if($(this).val() == 'company'){
                $('.company_name').slideDown('slow');
            } else {
                $('.company_name').slideUp('slow');
            }
        });
    })
</script>

<div class="container">
    <div class="row">
        <div class="col-md-12 block-auth">
            <div class="row">
                <div class="col-md-6">
                    <h3>SIGN UP</h3>



                    <form method="post" action="" class="form-horizontal">
                        <div class="form-group">
                            <label class="col-lg-5 control-label">First Name</label>
                            <div class="col-lg-6">
                                <input type="text" name="first_name" class="form-control" placeholder="First Name">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-5 control-label">Last Name</label>
                            <div class="col-lg-6">
                                <input type="text" name="last_name" class="form-control" placeholder="Last Name">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-5 control-label">Account type</label>
                            <div class="col-lg-6">
                                <select name="type_account">
                                    <option value="candidate">Candidate</option>
                                    <option value="company">Company</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group company_name" style="display:none;">
                            <label class="col-lg-5 control-label">Company Name</label>
                            <div class="col-lg-6">
                                <input type="text" class="form-control" placeholder="Company Name">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-5 control-label">Email Address</label>
                            <div class="col-lg-6">
                                <input type="email" name="email" class="form-control" placeholder="Email Address">
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-lg-5 control-label">Password</label>
                            <div class="col-lg-6">
                                <input type="password" name="password" class="form-control" placeholder="Password">
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-lg-5 control-label">Confirm Password</label>
                            <div class="col-lg-6">
                                <input type="password" class="form-control" name="conf_password" placeholder="Confirm Password">
                            </div>
                        </div>

                       <button class="btn btn-form btn-success pull-right">Sign Up</button>
                    </form>
                </div>
                <div class="col-md-6">
                    <div class="login-s">
                        <h3>or</h3>
                        <a class="btn btn-primary">Sign Up with Facebook</a>
                        <a class="btn btn-primary">Sign Up with Twitter</a>
                        <a class="btn btn-primary">SIgn Up with LinkedIn</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

